### PR TITLE
Package restructure

### PR DESCRIPTION
**Pull request by svilupp**
Changes that are standard part of JL packages at the registration point
- add docs (needs actual changes in the future...)
- add changelog
- restructure github actions and tests

I have NOT
- applied the SciML formatting, as it would obfuscate the changes I've made - if you're okay with it, let's run it in a separate PR
- update input types --> your function takes only a "String", we should broaden to AbstractString -- again, can do it as a separate PR

### CODE REVIEW

**Review by astariul — APPROVED** [review]
LGTM !

Thanks for the awesome PR, would love to see the next PR like you mentioned :D

**Comment by astariul** [comment]
@svilupp Any idea why the CI is not passing ? The [Github actions log](https://github.com/astariul/Sentencize.jl/actions/runs/10122724474/job/27996197390?pr=6) says :

> Run julia-actions/setup-julia@v2
  with:
    include-all-prereleases: false
    show-versioninfo: false
Error: Version input must not be null

But it's weird because the `version` is specified correctly in the yaml file ?

**Comment by svilupp** [comment]
I’ll debug it when I’m at the computer. The tests were fine locally but I’ll check it all later.

Btw can you give me contributor right to be able to run the workflows?

EDIT: I bet it’s just bad yaml formatting. I’ll look at it later

**Comment by svilupp** [comment]
I think it was just a keyword mismatch by copy&pasting across versions. Let's see

**Comment by astariul** [comment]
Awesome 👍

**Comment by astariul** [comment]
By the way I invited you to be a collaborator, let me know if you have any issue.

Thanks again for your work on this project !

**Pull request merged**
